/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectosistemas.frame;

import Animacion.Fade;
import com.proyectosistemas.fonts.Fuente;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Alejandro
 */
public class Login extends javax.swing.JFrame { //hacer un mouseentered en cualquier lado para que se active el cambio 

    /**
     * Creates new form Login
     */
    Fuente tipoFuente;
    Timer t;
    public static Exit exit = new Exit();
    //private Thread t1 = new Thread(new Thread1 ());
    Thread t1 = new Thread(new Runnable() {
        @Override
        public void run() {
            int exit = 0;
            while (exit == 0) {
                try {
                    t1.sleep(1200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/loggedin.gif")));
                    //t2.start();
                    exit++;
                } catch (InterruptedException ex) {
                    Logger.getLogger(Thread.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    });

    public Login() {
//        UsuarioLog usuarioLog = new UsuarioLog();
//        usuarioLog.logear("123", "123");
        tipoFuente = new Fuente();
        initComponents();
        this.setLocationRelativeTo(null); //hace que cuando se ejecuta el programa salga en el centro
        jLabel4.setFont(tipoFuente.fuente(tipoFuente.decker, 0, 18));
        jLabel3.setFont(tipoFuente.fuente(tipoFuente.decker, 0, 18));
        txtUserName.setFont(tipoFuente.fuente(tipoFuente.decker, 0, 18));
        jLabel28.setFont(tipoFuente.fuente(tipoFuente.decker, 1, 18));
        jLabel23.setFont(tipoFuente.fuente(tipoFuente.decker, 1, 18));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        Ejemplo6 = new javax.swing.JLabel();
        Ejemplo1 = new javax.swing.JLabel();
        Ejemplo3 = new javax.swing.JLabel();
        Ejemplo4 = new javax.swing.JLabel();
        Ejemplo5 = new javax.swing.JLabel();
        Ejemplo2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TopPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpIngreso = new javax.swing.JPanel();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        pnl1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        pnl2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenuPanel.setForeground(new java.awt.Color(255, 255, 255));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ejemplo6.setBackground(new java.awt.Color(255, 255, 255));
        Ejemplo6.setForeground(new java.awt.Color(255, 255, 255));
        Ejemplo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ejemplo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-questions-100.png"))); // NOI18N
        Ejemplo6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ejemplo6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Ejemplo6MouseMoved(evt);
            }
        });
        Ejemplo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ejemplo6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ejemplo6MouseExited(evt);
            }
        });
        MenuPanel.add(Ejemplo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 180, 160));

        Ejemplo1.setBackground(new java.awt.Color(255, 255, 255));
        Ejemplo1.setForeground(new java.awt.Color(255, 255, 255));
        Ejemplo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ejemplo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-questions-100.png"))); // NOI18N
        Ejemplo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ejemplo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Ejemplo1MouseMoved(evt);
            }
        });
        Ejemplo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ejemplo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ejemplo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ejemplo1MouseExited(evt);
            }
        });
        MenuPanel.add(Ejemplo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 150));

        Ejemplo3.setBackground(new java.awt.Color(255, 255, 255));
        Ejemplo3.setForeground(new java.awt.Color(255, 255, 255));
        Ejemplo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ejemplo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-questions-100.png"))); // NOI18N
        Ejemplo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ejemplo3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Ejemplo3MouseMoved(evt);
            }
        });
        Ejemplo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ejemplo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ejemplo3MouseExited(evt);
            }
        });
        MenuPanel.add(Ejemplo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 180, 160));

        Ejemplo4.setBackground(new java.awt.Color(255, 255, 255));
        Ejemplo4.setForeground(new java.awt.Color(255, 255, 255));
        Ejemplo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ejemplo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-questions-100.png"))); // NOI18N
        Ejemplo4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ejemplo4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Ejemplo4MouseMoved(evt);
            }
        });
        Ejemplo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ejemplo4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ejemplo4MouseExited(evt);
            }
        });
        MenuPanel.add(Ejemplo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 180, 160));

        Ejemplo5.setBackground(new java.awt.Color(255, 255, 255));
        Ejemplo5.setForeground(new java.awt.Color(255, 255, 255));
        Ejemplo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ejemplo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-questions-100.png"))); // NOI18N
        Ejemplo5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ejemplo5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Ejemplo5MouseMoved(evt);
            }
        });
        Ejemplo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ejemplo5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ejemplo5MouseExited(evt);
            }
        });
        MenuPanel.add(Ejemplo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, 160));

        Ejemplo2.setBackground(new java.awt.Color(255, 255, 255));
        Ejemplo2.setForeground(new java.awt.Color(255, 255, 255));
        Ejemplo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ejemplo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-questions-100.png"))); // NOI18N
        Ejemplo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ejemplo2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Ejemplo2MouseMoved(evt);
            }
        });
        Ejemplo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ejemplo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ejemplo2MouseExited(evt);
            }
        });
        MenuPanel.add(Ejemplo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 180, 160));

        jLabel10.setBackground(new java.awt.Color(0, 153, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Ejemplo #6");
        MenuPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, 20));

        jLabel16.setBackground(new java.awt.Color(0, 153, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("Ejemplo #1");
        MenuPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 190, 100, -1));

        jLabel17.setBackground(new java.awt.Color(0, 153, 255));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 255));
        jLabel17.setText("Ejemplo #2");
        MenuPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 20));

        jLabel18.setBackground(new java.awt.Color(0, 153, 255));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 255));
        jLabel18.setText("Ejemplo #3");
        MenuPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 20));

        jLabel19.setBackground(new java.awt.Color(0, 153, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 255));
        jLabel19.setText("Ejemplo #4");
        MenuPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, 20));

        jLabel20.setBackground(new java.awt.Color(0, 153, 255));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 255));
        jLabel20.setText("Ejemplo #5");
        MenuPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, 20));

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        TopPanel.setBackground(new java.awt.Color(255, 255, 255));
        TopPanel.setForeground(new java.awt.Color(255, 255, 255));
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-close-window-32_1.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        TopPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-minimize-window-32.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        TopPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, 40));

        getContentPane().add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jpIngreso.setPreferredSize(new java.awt.Dimension(290, 580));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        pnl1.setMinimumSize(new java.awt.Dimension(290, 580));
        pnl1.setName("pnl1"); // NOI18N
        pnl1.setPreferredSize(new java.awt.Dimension(290, 580));
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-customer-96.png"))); // NOI18N
        pnl1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 170));

        jLabel4.setBackground(new java.awt.Color(0, 153, 255));
        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Usuario:");
        pnl1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-customer-32.png"))); // NOI18N
        pnl1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-password-1-32.png"))); // NOI18N
        pnl1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnl1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 210, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        pnl1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-show-password-30.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        pnl1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 30, 40));

        jLabel3.setBackground(new java.awt.Color(0, 153, 255));
        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Contraseña:");
        pnl1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 30));

        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("Ingrese el usuario...");
        txtUserName.setToolTipText("");
        txtUserName.setBorder(null);
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });
        pnl1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, 30));

        txtPassword.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("password123456");
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPassword.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPasswordMouseExited(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        pnl1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 170, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-enter-100.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, 90));

        jPanelSlider1.add(pnl1, "card2");

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        pnl2.setMinimumSize(new java.awt.Dimension(290, 580));
        pnl2.setName("pnl2"); // NOI18N
        pnl2.setPreferredSize(new java.awt.Dimension(290, 580));
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/frameinitial.png"))); // NOI18N
        pnl2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 170));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 204));
        jLabel23.setText("Bienvenido, usuario!");
        pnl2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 200, 50));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 204));
        jLabel28.setText("Login exitoso!");
        pnl2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 130, 50));

        jPanelSlider1.add(pnl2, "card2");

        pnl3.setBackground(new java.awt.Color(255, 255, 255));
        pnl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        pnl3.setMinimumSize(new java.awt.Dimension(290, 580));
        pnl3.setName("pnl3"); // NOI18N
        pnl3.setPreferredSize(new java.awt.Dimension(290, 580));
        pnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 204));
        jLabel25.setText("ingresados e intente de nuevo!");
        pnl3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 50));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 204));
        jLabel26.setText("Login fallido! Verifica los datos");
        pnl3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 300, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-arrow-pointing-left-100.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pnl3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 180));

        jPanelSlider1.add(pnl3, "card2");

        jpIngreso.add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.exit.setVisible(true);

    }//GEN-LAST:event_jLabel21MouseClicked

    private void Ejemplo1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo1MouseMoved
        Ejemplo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_Ejemplo1MouseMoved

    private void Ejemplo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo1MouseExited
        Ejemplo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_Ejemplo1MouseExited

    private void Ejemplo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo2MouseExited
        Ejemplo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_Ejemplo2MouseExited

    private void Ejemplo2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo2MouseMoved
        Ejemplo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_Ejemplo2MouseMoved

    private void Ejemplo3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo3MouseMoved
        Ejemplo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_Ejemplo3MouseMoved

    private void Ejemplo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo3MouseExited
        Ejemplo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_Ejemplo3MouseExited

    private void Ejemplo4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo4MouseMoved
        Ejemplo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_Ejemplo4MouseMoved

    private void Ejemplo4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo4MouseExited
        Ejemplo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_Ejemplo4MouseExited

    private void Ejemplo5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo5MouseMoved
        Ejemplo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_Ejemplo5MouseMoved

    private void Ejemplo5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo5MouseExited
        Ejemplo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_Ejemplo5MouseExited

    private void Ejemplo6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo6MouseMoved
        Ejemplo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_Ejemplo6MouseMoved

    private void Ejemplo6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo6MouseExited
        Ejemplo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_Ejemplo6MouseExited

    private void Ejemplo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo1MouseClicked

        JFrame marco = new MarcoRebote();

        marco.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        marco.setVisible(true);

    }//GEN-LAST:event_Ejemplo1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.logear();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked


    }//GEN-LAST:event_jButton1MouseClicked

    private void txtPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseExited
        //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/smilemonkey.gif")));
    }//GEN-LAST:event_txtPasswordMouseExited

    private void txtPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseEntered
        //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/seenoevil.gif")));
    }//GEN-LAST:event_txtPasswordMouseEntered

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.selectAll();
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        txtUserName.selectAll();
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        txtPassword.setEchoChar('●');
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-show-password-30.png")));
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        txtPassword.setEchoChar((char) 0);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/icons8-show-password-30 (1).png")));
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setToolTipText("Oprimir para mostrar la contraseña.");
    }//GEN-LAST:event_jLabel5MouseEntered

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.logear();

        }

    }//GEN-LAST:event_txtUserNameKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.logear();

        }

    }//GEN-LAST:event_txtPasswordKeyPressed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered

        //jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/Enter_ON.png")));

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyectosistemas/image/Enter_OFF.png")));

    }//GEN-LAST:event_jButton1MouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.Ejemplo1.setEnabled(false);
        this.Ejemplo5.setEnabled(false);
        this.Ejemplo2.setEnabled(false);
        this.Ejemplo4.setEnabled(false);
        this.Ejemplo6.setEnabled(false);
        this.Ejemplo3.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void Ejemplo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo1MouseEntered


    }//GEN-LAST:event_Ejemplo1MouseEntered

    private void Ejemplo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo2MouseEntered

    }//GEN-LAST:event_Ejemplo2MouseEntered

    private void Ejemplo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo3MouseEntered

    }//GEN-LAST:event_Ejemplo3MouseEntered

    private void Ejemplo4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo4MouseEntered

    }//GEN-LAST:event_Ejemplo4MouseEntered

    private void Ejemplo5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo5MouseEntered

    }//GEN-LAST:event_Ejemplo5MouseEntered

    private void Ejemplo6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejemplo6MouseEntered

    }//GEN-LAST:event_Ejemplo6MouseEntered

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jPanelSlider1.nextPanel(20, pnl1, jPanelSlider1.right);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">sdadsdadadada
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ejemplo1;
    private javax.swing.JLabel Ejemplo2;
    private javax.swing.JLabel Ejemplo3;
    private javax.swing.JLabel Ejemplo4;
    private javax.swing.JLabel Ejemplo5;
    private javax.swing.JLabel Ejemplo6;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    public void logear() {

        String nombreUsuario = "admin";
//
        String contrasenna = "12345";

        if (nombreUsuario.equalsIgnoreCase(txtUserName.getText()) && contrasenna.equalsIgnoreCase(txtPassword.getText())) {
            jPanelSlider1.nextPanel(20, pnl2, jPanelSlider1.left);
            this.Ejemplo1.setEnabled(true);
            this.Ejemplo2.setEnabled(true);
            this.Ejemplo3.setEnabled(true);
            this.Ejemplo4.setEnabled(true);
            this.Ejemplo5.setEnabled(true);
            this.Ejemplo6.setEnabled(true);
            t1.start();
        } else {
            jPanelSlider1.nextPanel(20, pnl3, jPanelSlider1.left);
        }
//
//        Usuario usuarioLogeado = new Usuario();
//
//        try {
//            UsuarioLog usuarioLog = new UsuarioLog();
//
//            usuarioLogeado = usuarioLog.logear(nombreUsuario, contrasenna);
//
//            if (usuarioLogeado != null) {
//
//                if (usuarioLogeado.isSuperAdmi()) {
//
//                    // rSPanelsSlider1.setPanelSlider(15, pnl2, RSPanelsSlider.DIRECT.LEFT);
//                    jPanelSlider1.nextPanel(20, pnl2, jPanelSlider1.left);
//                    this.labelAnnadir.setEnabled(true);
//                    this.labelAnnadirEventos.setEnabled(true);
//                    this.labelInventario.setEnabled(true);
//                    this.labelManejarEntradas.setEnabled(true);
//                    this.labelManejarEventos.setEnabled(true);
//                    this.labelVentaEntradas.setEnabled(true);
//                    t1.start();
//                }
//
//            } else {
//                //rSPanelsSlider1.setPanelSlider(15, pnl3, RSPanelsSlider.DIRECT.LEFT);
//                jPanelSlider1.nextPanel(20, pnl3, jPanelSlider1.left);
//                labelAnnadir.setEnabled(false);
//            }
//
//        } catch (Exception e) {
//
//            e.printStackTrace();
//
//        }

    }

}
